language: ruby

branches:
  only:
  - master
rvm:
- 2.2.3
t
before_script:
 - chmod +x ./script/cibuild

script: ./script/cibuild
exclude: [vendor]
sudo: false

#How-to: https://ayastreb.me/deploy-jekyll-to-github-pages-with-travis-ci/