language: ruby
cache: bundler
branches:
  only:
  - master
script:
  - JEKYLL_ENV=production bundle exec jekyll build --destination travis_build
deploy:
  provider: pages
  local-dir: ./travis_build
  target-branch: master
  email: deploy@travis-ci.org
  name: Deployment Bot
  skip-cleanup: true
  github_token: $GITHUB_TOKEN 
  keep-history: true
  on:
    branch: master