# Site settings
title: Yet Another Minimal Theme
description: "Yet Another Minimal Theme"
url:  "http://localhost:4000"
author:
  name: "Alessio Franceschi"
  email: "alessiofranceschi2@gmail.com"
  url: "https://alessiofranceschi.me"

permalink: /:year/:month/:day/:title:output_ext


plugins: [jekyll-paginate]

#Pagination
paginate: 3
paginate_path: "/page:num/"