#Google Analytics
analytics-id: #leave blank to not use Analytics

#Disqus
disqus:
  disqus_shortname: "your_username" #Your disqus shortname. Leave blank to deactivate disqus comments

#Show categories at the end of posts
categories:
  active: true

#Show date and read time under the post title
date-under-post:
  active: true

#Use MathJAX
mathjax:
  active: true

#Show related posts based on categories
related-posts:
  active: true
  title: "You May Also Enjoy"

lazyload:
  active: false